[package]
name = "smhesly"
version = "0.1.0"
authors = ["Jørund B. Fagerjord <j.b.fagerjord@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
protoc-rust-grpc = "0.6.1"
